# golangci-lint configuration (v2)
# For more information: https://golangci-lint.run/

version: "2"

# Linters to enable
linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - misspell      # Find commonly misspelled words
    - gocritic      # Comprehensive Go linter
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - bodyclose     # Check HTTP response body closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - prealloc      # Find slice declarations that could be preallocated
    - nilerr        # Find code that returns nil even if error is not nil

# Formatters to enable
formatters:
  enable:
    - goimports     # Check import formatting and organization
