# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - typecheck     # Type-check Go code
    - unused        # Check for unused code
    - gofmt         # Check code formatting
    - goimports     # Check import formatting
    - misspell      # Find commonly misspelled words
    - gocritic      # Comprehensive Go linter
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - bodyclose     # Check HTTP response body closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - prealloc      # Find slice declarations that could be preallocated
    - exportloopref # Check for loop variable capture issues
    - nilerr        # Find code that returns nil even if error is not nil

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow

  gofmt:
    simplify: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gosec:
    excludes:
      - G404 # Use of weak random number generator (math/rand instead of crypto/rand)
    severity: medium
    confidence: medium

  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam

    # Allow dot imports in test files for testify
    - path: _test\.go
      text: "dot imports"

    # Mathematical constants with many digits
    - path: const\.go
      linters:
        - gomnd

  # Show all issues
  exclude-dirs:
    - vendor
    - coverage

  exclude-files:
    - ".*\\.pb\\.go$"
