name: 'Setup Go Environment'
description: 'Install Go, download and verify module dependencies'

inputs:
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.24'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Download dependencies
      shell: bash
      run: go mod download

    - name: Verify dependencies
      shell: bash
      run: go mod verify
